#!/bin/bash

CHOICE=$(zenity --question --no-wrap --text "You pressed the exit shortcut. Do you really want to exit i3? This will end your X session." --ok-label="Yes, exit i3" --cancel-label="No")
case $? in
    0)
        i3-msg exit;;
esac