#!/usr/bin/env bash

# Files and cmd
cfg="$HOME/.config/eww/dock"

# Terminate eww
killall -q eww

# Wait until processes have been shut down
while pgrep -u $UID -x eww >/dev/null; do sleep 1; done

# Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	eww daemon
	sleep 3
fi

# Open widgets
eww --config "$cfg" open-many apps

# Monitor dock
$HOME/.local/src/monitor-dock &

# Autohide dock
dock_id=$(xdo id -m -a "Eww - apps")
xdo show $dock_id
hideIt.sh --id $dock_id --hover -d bottom -s 3 -p 10 -i 10 >/dev/null 2>&1 &
