#!/bin/bash

# Verify number of arguments given
if [ $# -lt 1 ] || [ $1 == "--help" ] || [ $1 == "-h" ]; then
  echo "Usage: save-theme THEME_NAME"
  exit 1
fi

# Define theme file locations
GTK3_FILE_LOCATION="$HOME/.config/gtk-3.0/settings.ini"
QT_FILE_LOCATION="$HOME/.config/qt5ct/qt5ct.conf"
ALACRITTY_FILE_LOCATION="$HOME/.config/alacritty/alacritty.yml"
ROFI_FILE_LOCATION="$HOME/.config/rofi/config.rasi"
POLYBAR_FILE_LOCATION="$HOME/scripts/launch-polybar.sh"
BG_SAVED_LOCATION="$HOME/.config/nitrogen/bg-saved.cfg"

# 1) Get GTK theme
gtk_theme_name=$(cat "$GTK3_FILE_LOCATION" | sed -n "s/gtk-theme-name=//p")
gtk_icon_theme_name=$(cat "$GTK3_FILE_LOCATION" | sed -n "s/gtk-icon-theme-name=//p")
gtk_cursor_theme_name=$(cat "$GTK3_FILE_LOCATION" | sed -n "s/gtk-cursor-theme-name=//p")
gtk_font_name=$(cat "$GTK3_FILE_LOCATION" | sed -n "s/gtk-font-name=//p")

# 2) Get QT theme
qt_color_scheme_path=$(cat "$QT_FILE_LOCATION" | sed -n "s/color_scheme_path=//p" | sed "s:$HOME:"'$HOME'":")
qt_icon_theme=$(cat "$QT_FILE_LOCATION" | sed -n "s/icon_theme=//p")
qt_fixed=$(cat "$QT_FILE_LOCATION" | sed -n "s/fixed=//p")
qt_general=$(cat "$QT_FILE_LOCATION" | sed -n "s/general=//p")

# 3) Get Alacritty theme
alacritty_theme=$(cat "$ALACRITTY_FILE_LOCATION" | sed -n "s:\s*- ~/\.config/alacritty/::p")

# 4) Get Rofi theme
rofi_theme=$(cat "$ROFI_FILE_LOCATION" | sed -n "s/@import\s*\"// ; s/\/.*//p")

# 5) Get Polybar theme
polybar_style=$(cat "$POLYBAR_FILE_LOCATION" | sed -n "s/style=//p")

# 6) Get wallpaper
wallpaper_file=$(cat "$BG_SAVED_LOCATION" | sed -n "s/file=//p" | sed "s:$HOME:"'$HOME'":")
wallpaper_mode=$(cat "$BG_SAVED_LOCATION" | sed -n "s/mode=//p")
wallpaper_bgcolor=$(cat "$BG_SAVED_LOCATION" | sed -n "s/bgcolor=//p")

# Save theme
cat << EOF > "$HOME/.desktop-theme/$1.theme"
GTK_THEME_NAME="$gtk_theme_name"
GTK_ICON_THEME_NAME="$gtk_icon_theme_name"
GTK_CURSOR_THEME_NAME="$gtk_cursor_theme_name"
GTK_FONT_NAME="$gtk_font_name"
QT_COLOR_SCHEME_PATH="$qt_color_scheme_path"
QT_ICON_THEME="$qt_icon_theme"
QT_FIXED="$qt_fixed"
QT_GENERAL="$qt_general"
ALACRITTY_THEME="$alacritty_theme"
ROFI_THEME="$rofi_theme"
POLYBAR_STYLE=$polybar_style
WALLPAPER_FILE="$wallpaper_file"
WALLPAPER_MODE="$wallpaper_mode"
WALLPAPER_BGCOLOR="$wallpaper_bgcolor"
EOF
